<?php

namespace Tests\Integration\Filters;

use App\Filters\TransactionsConditionFilter;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class TransactionsConditionFilterTest extends TestCase
{
    use DatabaseMigrations;

    protected $filter;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->filter = new TransactionsConditionFilter();
    }

    public function testFilterSuccess()
    {
    }
}
